/* This file was generated by blade */

extern const int kSvnInfoCount;
extern const char* const kSvnInfo[];
extern const char kBuildType[];
extern const char kBuildTime[];
extern const char kBuilderName[];
extern const char kHostName[];
extern const char kCompiler[];
const int kSvnInfoCount = 1;
const char* const kSvnInfo[1] = {"commit 1b892deb618f6200fb1fca049f8c01cda1b13960\n"
"Author: junchaoyan <junchaoyan@tencent.com>\n"
"Date:   Mon Mar 9 21:55:13 2020 +0800\n"
"\n"
"    update gitignore\n"
""};
const char kBuildType[] = "release";
const char kBuildTime[] = "Mon Mar 16 15:38:00 2020";
const char kBuilderName[] = "junchaoyan";
const char kHostName[] = "VM_147_101_centos";
const char kCompiler[] = "GCC 4.8.5";
